name: test_workflow
on: push 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: hexlet-components/hello-from-hexlet-action@release
      - run: make setup
      - run: make test
      - run: make lint